import type { NoiseSnapshotPayload, NoiseZone } from "@/lib/noiseTypes";

interface NoiseBaselineEntry {
  station_id: number;
  name: string;
  city: string;
  state: string;
  zone: NoiseZone;
  lat: number;
  lng: number;
  laf: number;
  lcf: number;
  las: number;
  lcs: number | null;
  lae: number | null;
  lce: number | null;
  lpeak: number;
  max: number;
  min: number;
  battery: number;
}

export const SNAPSHOT_CAPTURED_AT = "2026-03-14T05:15:00.000Z";

export const BASELINE: Record<number, NoiseBaselineEntry> = {
  284: {
    station_id: 284,
    name: "Bangalore — Church Street",
    city: "Bangalore",
    state: "Karnataka",
    zone: "Commercial",
    lat: 12.9716,
    lng: 77.5946,
    laf: 57.9,
    lcf: 62.7,
    las: 57.8,
    lcs: 62.8,
    lae: 59.5,
    lce: 67.3,
    lpeak: 68.19,
    max: 70.8,
    min: 51.0,
    battery: 13.75,
  },
  287: {
    station_id: 287,
    name: "Delhi — Anand Vihar",
    city: "Delhi",
    state: "Delhi",
    zone: "Residential",
    lat: 28.6458,
    lng: 77.3152,
    laf: 71.2,
    lcf: 75.8,
    las: 70.9,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 84.3,
    max: 89.1,
    min: 63.2,
    battery: 13.5,
  },
  291: {
    station_id: 291,
    name: "Mumbai — Bandra",
    city: "Mumbai",
    state: "Maharashtra",
    zone: "Residential",
    lat: 19.0596,
    lng: 72.8295,
    laf: 62.3,
    lcf: 67.1,
    las: 61.8,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 74.5,
    max: 78.2,
    min: 54.1,
    battery: 13.5,
  },
  293: {
    station_id: 293,
    name: "Delhi — IGI Airport",
    city: "Delhi",
    state: "Delhi",
    zone: "Industrial",
    lat: 28.5562,
    lng: 77.1,
    laf: 74.1,
    lcf: 79.8,
    las: 73.6,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 88.2,
    max: 92.4,
    min: 67.3,
    battery: 13.5,
  },
  296: {
    station_id: 296,
    name: "Lucknow — SGPGI Hospital",
    city: "Lucknow",
    state: "Uttar Pradesh",
    zone: "Silence",
    lat: 26.8467,
    lng: 80.9462,
    laf: 50.6,
    lcf: 70.7,
    las: 50.6,
    lcs: 71.5,
    lae: 51.0,
    lce: 71.5,
    lpeak: 68.19,
    max: 63.4,
    min: 49.2,
    battery: 13.75,
  },
  300: {
    station_id: 300,
    name: "Chennai — Anna Nagar",
    city: "Chennai",
    state: "Tamil Nadu",
    zone: "Commercial",
    lat: 13.0843,
    lng: 80.2101,
    laf: 63.4,
    lcf: 68.2,
    las: 62.9,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 75.6,
    max: 79.3,
    min: 55.8,
    battery: 13.5,
  },
  305: {
    station_id: 305,
    name: "Chennai — Marina Beach",
    city: "Chennai",
    state: "Tamil Nadu",
    zone: "Residential",
    lat: 13.0499,
    lng: 80.2824,
    laf: 60.2,
    lcf: 65.1,
    las: 59.8,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 72.8,
    max: 76.5,
    min: 53.4,
    battery: 13.5,
  },
  308: {
    station_id: 308,
    name: "Hyderabad — Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    zone: "Residential",
    lat: 17.4126,
    lng: 78.4071,
    laf: 58.7,
    lcf: 63.4,
    las: 58.2,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 71.2,
    max: 74.8,
    min: 51.3,
    battery: 13.5,
  },
  312: {
    station_id: 312,
    name: "Kolkata — Park Street",
    city: "Kolkata",
    state: "West Bengal",
    zone: "Commercial",
    lat: 22.5512,
    lng: 88.3517,
    laf: 65.8,
    lcf: 70.3,
    las: 65.2,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 78.4,
    max: 82.1,
    min: 58.6,
    battery: 13.5,
  },
  317: {
    station_id: 317,
    name: "Mumbai — Dadar",
    city: "Mumbai",
    state: "Maharashtra",
    zone: "Commercial",
    lat: 19.0178,
    lng: 72.8478,
    laf: 67.4,
    lcf: 72.1,
    las: 66.9,
    lcs: null,
    lae: null,
    lce: null,
    lpeak: 79.6,
    max: 83.8,
    min: 59.7,
    battery: 13.5,
  },
};

export const BASELINE_STATION_IDS = Object.keys(BASELINE)
  .map(Number)
  .sort((left, right) => left - right);

export function getSnapshotFromBaseline(stationId: number): NoiseSnapshotPayload | null {
  const baseline = BASELINE[stationId];
  if (!baseline) return null;

  return {
    station_id: baseline.station_id,
    name: baseline.name,
    city: baseline.city,
    state: baseline.state,
    zone: baseline.zone,
    lat: baseline.lat,
    lng: baseline.lng,
    laf: baseline.laf,
    las: baseline.las,
    lcf: baseline.lcf,
    lcs: baseline.lcs,
    lae: baseline.lae,
    lce: baseline.lce,
    lpeak: baseline.lpeak,
    lpeak_day: null,
    max: baseline.max,
    min: baseline.min,
    battery: baseline.battery,
    snapshot_taken: SNAPSHOT_CAPTURED_AT,
    source: "snapshot",
  };
}
